package com.nexamart.backend.repository;
import com.nexamart.backend.domain.*;import org.springframework.data.domain.*;import org.springframework.data.jpa.repository.*;import org.springframework.data.repository.query.Param;import java.time.Instant;
public interface OrderRepository extends JpaRepository<Order,Long>{Page<Order> findByCustomerId(Long id,Pageable p);Page<Order> findByDeliveryPartnerId(Long id,Pageable p);Page<Order> findByStatus(OrderStatus status,Pageable p);long countByStatus(OrderStatus s);long countByCreatedAtBetween(Instant a,Instant b);long countByStatusAndCreatedAtBetween(OrderStatus s,Instant a,Instant b);long countByDeliveryPartnerIdAndStatus(Long id,OrderStatus s);@Query("select o from Order o where (:status is null or o.status=:status) and (:q is null or cast(o.id as string) like concat('%',:q,'%') or lower(o.customer.name) like lower(concat('%',:q,'%')) or lower(o.customer.email) like lower(concat('%',:q,'%'))) and (:fromDate is null or o.createdAt>=:fromDate) and (:toDate is null or o.createdAt<:toDate)")Page<Order> adminSearch(@Param("q")String q,@Param("status")OrderStatus status,@Param("fromDate")Instant fromDate,@Param("toDate")Instant toDate,Pageable p);@Query("select o from Order o where o.deliveryPartner.id=:id and (:status is null or o.status=:status) and (:q is null or cast(o.id as string) like concat('%',:q,'%') or lower(o.customer.name) like lower(concat('%',:q,'%'))) and (:fromDate is null or o.createdAt>=:fromDate) and (:toDate is null or o.createdAt<:toDate)")Page<Order> partnerSearch(@Param("id")Long id,@Param("q")String q,@Param("status")OrderStatus status,@Param("fromDate")Instant fromDate,@Param("toDate")Instant toDate,Pageable p);@Query("select o from Order o left join o.deliveryPartner dp where ((dp.id=:id) or (dp is null and o.status in :openStatuses)) and (:q is null or cast(o.id as string) like concat('%',:q,'%') or lower(o.customer.name) like lower(concat('%',:q,'%'))) and (:status is null or o.status=:status) and (:fromDate is null or o.createdAt>=:fromDate) and (:toDate is null or o.createdAt<:toDate) order by o.createdAt desc") Page<Order> partnerSearchIncludingOpen(@Param("id")Long id,@Param("q")String q,@Param("status")OrderStatus status,@Param("fromDate")Instant fromDate,@Param("toDate")Instant toDate,@Param("openStatuses")java.util.Collection<OrderStatus> openStatuses,Pageable p);
 @Lock(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE)@Query("select o from Order o where o.id=:id")java.util.Optional<Order> findByIdForUpdate(@Param("id")Long id);
 @Query("select o.id from Order o where o.deliveryStatus=:placed and o.deliveryPartner is null and o.createdAt>=:since and (o.paymentMethod=:cod or o.paymentStatus=:paid) order by o.createdAt asc")java.util.List<Long> findIdsAwaitingDispatch(@Param("placed")DeliveryStatus placed,@Param("since")Instant since,@Param("cod")PaymentMethod cod,@Param("paid")PaymentStatus paid);
 long countByDeliveryPartnerIdAndDeliveryStatus(Long id,DeliveryStatus s);
 long countByDeliveryPartnerIdAndDeliveryStatusIn(Long id,java.util.Collection<DeliveryStatus> s);
 long countByDeliveryStatus(DeliveryStatus s);
 @Query("select o from Order o where o.deliveryPartner.id=:id and o.deliveryStatus in :statuses and (:q is null or cast(o.id as string) like concat('%',:q,'%') or lower(o.customer.name) like lower(concat('%',:q,'%')))")Page<Order> partnerOrders(@Param("id")Long id,@Param("statuses")java.util.Collection<DeliveryStatus> statuses,@Param("q")String q,Pageable p);}
