package com.nexamart.backend.service;
import com.nexamart.backend.api.ApiModels.*;import com.nexamart.backend.domain.*;import com.nexamart.backend.exception.ApiException;import com.nexamart.backend.repository.*;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.time.*;import java.util.*;
@Service public class AdminService{final OrderRepository orders;final UserAccountRepository users;final ProductRepository products;final CategoryRepository cats;final DeliveryPartnerProfileRepository profiles;final MappingService map;final NotificationRepository notifications;final DeliveryDispatchService dispatch;public AdminService(OrderRepository o,UserAccountRepository u,ProductRepository p,CategoryRepository c,DeliveryPartnerProfileRepository pr,MappingService m,NotificationRepository n,DeliveryDispatchService d){orders=o;users=u;products=p;cats=c;profiles=pr;map=m;notifications=n;dispatch=d;}
 public DashboardResponse dashboard(){Instant now=Instant.now(),start=now.minus(1,java.time.temporal.ChronoUnit.DAYS);long total=orders.count(),today=orders.countByCreatedAtBetween(start,now),pending=orders.countByDeliveryStatus(DeliveryStatus.ORDER_PLACED)+orders.countByDeliveryStatus(DeliveryStatus.DELIVERY_ASSIGNED)+orders.countByDeliveryStatus(DeliveryStatus.PACKING),ofd=orders.countByDeliveryStatus(DeliveryStatus.ON_THE_WAY)+orders.countByDeliveryStatus(DeliveryStatus.ARRIVED),del=orders.countByStatusAndCreatedAtBetween(OrderStatus.DELIVERED,start,now);BigDecimal sales=orders.findAll(Pageable.unpaged()).stream().filter(o->o.getCreatedAt().isAfter(start)&&o.getStatus()!=OrderStatus.CANCELLED).map(Order::getTotal).reduce(BigDecimal.ZERO,BigDecimal::add);List<AdminRecentOrder> recent=orders.findAll(PageRequest.of(0,5,Sort.by(Sort.Direction.DESC,"createdAt"))).getContent().stream().map(o->new AdminRecentOrder(o.getId().toString(),o.getCustomer().getName(),o.getTotal().doubleValue(),o.getDeliveryStatus().name(),o.getCreatedAt().toString())).toList();
List<Notification> adminNotes=notifications.findTop20ByUserRoleOrderByCreatedAtDesc(Role.ADMIN);
long unread=notifications.countByUserRoleAndReadFlagFalse(Role.ADMIN);
List<AdminNotificationResponse> notificationRows=adminNotes.stream().map(n->new AdminNotificationResponse(n.getId().toString(),n.getTitle(),n.getMessage(),n.getCreatedAt(),n.isReadFlag(),n.getOrderId())).toList();
return new DashboardResponse(total,today,pending,ofd,del,sales.doubleValue(),"INR",recent,unread,notificationRows);}
 public PageResponse<OrderResponse> orderPage(int page,int size,String q,OrderStatus status,Instant from,Instant to){Page<Order> p=orders.adminSearch(q,status,from,to,PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt")));return new PageResponse<>(p.getContent().stream().map(map::order).toList(),p.getNumber(),p.getSize(),p.getTotalPages(),p.getTotalElements(),p.hasNext());}
 public OrderResponse detail(Long id){return map.order(orders.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Order not found.")));}
 @Transactional public void status(Long id,OrderStatusRequest r){Order o=get(id);if(o.getDeliveryStatus()!=DeliveryStatus.ORDER_PLACED)throw new ApiException(HttpStatus.CONFLICT,"Delivery progress is updated by the assigned delivery partner.");OrderStatus target=parse(r.status());if(!validAdmin(o.getStatus(),target))throw new ApiException(HttpStatus.CONFLICT,"Invalid order status transition.");o.setStatus(target);orders.save(o);}
 public void cancel(Long id,CancelRequest r){dispatch.cancel(id,r==null?null:r.reason());}
 /** Admin override: (re)assigns an order to a specific partner using the same atomic claim as automatic dispatch. */ public void assign(Long id,AssignRequest r){dispatch.adminAssign(id,r.deliveryPartnerId());}
 public PageResponse<CustomerResponse> customers(int page,int size,String q,AccountStatus status){Page<UserAccount> p=users.search(Role.CUSTOMER,q,status,PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt")));return new PageResponse<>(p.getContent().stream().map(this::customer).toList(),p.getNumber(),p.getSize(),p.getTotalPages(),p.getTotalElements(),p.hasNext());}
 public CustomerResponse customerDetail(Long id){UserAccount u=users.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Customer not found."));if(u.getRole()!=Role.CUSTOMER)throw new ApiException(HttpStatus.NOT_FOUND,"Customer not found.");return customer(u);}
 public void customerAction(Long id,ActionRequest r){UserAccount u=users.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Customer not found."));switch(r.action().toUpperCase()){case "ACTIVATE","REACTIVATE"->u.setStatus(AccountStatus.ACTIVE);case "DEACTIVATE"->u.setStatus(AccountStatus.INACTIVE);case "SUSPEND"->u.setStatus(AccountStatus.SUSPENDED);default->throw new ApiException(HttpStatus.BAD_REQUEST,"Unsupported customer action.");}users.save(u);}
 public PageResponse<DeliveryPartnerResponse> partners(int page,int size,String q,AccountStatus status){Page<UserAccount> p=users.search(Role.DELIVERY_PARTNER,q,status,PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"createdAt")));return new PageResponse<>(p.getContent().stream().map(this::partner).toList(),p.getNumber(),p.getSize(),p.getTotalPages(),p.getTotalElements(),p.hasNext());}
 public DeliveryPartnerResponse partnerDetail(Long id){return partner(users.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Delivery partner not found.")));}
 public void partnerAction(Long id,ActionRequest r){UserAccount u=users.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Delivery partner not found."));switch(r.action().toUpperCase()){case "ACTIVATE","REACTIVATE"->u.setStatus(AccountStatus.ACTIVE);case "DEACTIVATE"->u.setStatus(AccountStatus.INACTIVE);case "SUSPEND"->u.setStatus(AccountStatus.SUSPENDED);default->throw new ApiException(HttpStatus.BAD_REQUEST,"Unsupported partner action.");}users.save(u);}
 private CustomerResponse customer(UserAccount u){return new CustomerResponse(u.getId().toString(),u.getName(),u.getPhone(),u.getEmail(),null,u.getStatus().name(),u.getCreatedAt(),u.getLastActiveAt(),orders.findByCustomerId(u.getId(),Pageable.unpaged()).getTotalElements(),orders.findByCustomerId(u.getId(),Pageable.unpaged()).getContent().stream().map(Order::getTotal).filter(Objects::nonNull).reduce(BigDecimal.ZERO,BigDecimal::add),"INR",null,List.of("ACTIVATE","DEACTIVATE","SUSPEND"));}
 private DeliveryPartnerResponse partner(UserAccount u){long active=orders.countByDeliveryPartnerIdAndDeliveryStatusIn(u.getId(),DeliveryStatus.ACTIVE);long completed=orders.countByDeliveryPartnerIdAndDeliveryStatus(u.getId(),DeliveryStatus.DELIVERED);DeliveryPartnerProfile p=profiles.findById(u.getId()).orElse(null);String availability=p!=null&&p.isAvailable()?"ONLINE":"OFFLINE";String workState=active>0?"ON_DELIVERY":"IDLE";boolean assignable=p!=null&&p.isAvailable()&&u.getStatus()==AccountStatus.ACTIVE&&active==0&&profiles.findActiveOrderId(u.getId())==null;var stats=new DeliveryPartnerStatistics(completed+active,completed,orders.countByDeliveryPartnerIdAndDeliveryStatus(u.getId(),DeliveryStatus.CANCELLED),active);var current=orders.findByDeliveryPartnerId(u.getId(),Pageable.unpaged()).getContent().stream().filter(o->o.getDeliveryStatus().isActive()).limit(10).map(o->new PartnerOrderSummary(o.getId().toString(),o.getDeliveryStatus().name(),o.getUpdatedAt().toString())).toList();var history=orders.findByDeliveryPartnerId(u.getId(),Pageable.ofSize(10)).getContent().stream().filter(o->o.getDeliveryStatus().isTerminal()).map(o->new PartnerOrderSummary(o.getId().toString(),o.getDeliveryStatus().name(),o.getUpdatedAt().toString())).toList();return new DeliveryPartnerResponse(u.getId().toString(),u.getName(),u.getPhone(),u.getEmail(),null,u.getStatus().name(),p==null?"PENDING":p.getVerificationStatus(),availability,workState,u.getCreatedAt().toString(),u.getLastActiveAt()==null?null:u.getLastActiveAt().toString(),p==null?null:p.getVehicleType(),p==null?null:p.getVehicleNumber(),p==null?null:p.getLicenseReference(),stats,current,history,assignable,List.of("ACTIVATE","DEACTIVATE","SUSPEND","REACTIVATE"));}
 private Order get(Long id){return orders.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Order not found."));}private OrderStatus parse(String s){try{return OrderStatus.valueOf(s.toUpperCase());}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"Unknown order status.");}}private boolean validAdmin(OrderStatus a,OrderStatus b){return switch(a){case PENDING->b==OrderStatus.CONFIRMED||b==OrderStatus.CANCELLED;case CONFIRMED->b==OrderStatus.PREPARING||b==OrderStatus.CANCELLED;case PREPARING->b==OrderStatus.READY||b==OrderStatus.CANCELLED;default->false;};}
}
