package com.nexamart.customer.presentation.auth

import android.view.inputmethod.InputMethodManager
import androidx.core.content.getSystemService
import androidx.fragment.app.Fragment
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.nexamart.customer.R
import com.nexamart.customer.core.userMessage
import com.nexamart.customer.databinding.ViewOtpLoginBinding
import com.nexamart.customer.presentation.common.launchOnStarted
import com.nexamart.customer.presentation.common.visibleIf
import com.nexamart.customer.repository.SessionRepository
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

data class OtpState(
    val sending: Boolean = false,
    val verifying: Boolean = false,
    val otpSent: Boolean = false,
    /** Only present when the backend itself returns a development OTP; never generated by the app. */
    val debugOtp: String? = null,
    val prefillOtp: String? = null,
)

sealed interface OtpEvent {
    data class Message(val text: String) : OtpEvent
    data object Authenticated : OtpEvent
}

/** Port of OtpLoginView (customer OTP endpoints only). */
class OtpLoginViewModel(private val session: SessionRepository) : ViewModel() {
    private val _state = MutableStateFlow(OtpState())
    val state: StateFlow<OtpState> = _state.asStateFlow()
    private val _events = Channel<OtpEvent>(Channel.BUFFERED)
    val events = _events.receiveAsFlow()

    private fun digits(raw: String) = raw.replace(Regex("""\D"""), "")

    fun sendOtp(rawPhone: String) {
        val s = _state.value
        if (s.sending || s.verifying) return
        val phone = digits(rawPhone)
        if (!PHONE.matches(phone)) {
            _events.trySend(OtpEvent.Message("Enter a valid 10-digit mobile number."))
            return
        }
        _state.update { it.copy(sending = true) }
        viewModelScope.launch {
            try {
                val result = session.sendOtp(phone)
                _state.update {
                    it.copy(otpSent = result.success, debugOtp = result.debugOtp, prefillOtp = result.debugOtp?.takeIf { o -> o.isNotEmpty() })
                }
                _events.send(
                    OtpEvent.Message(
                        if (result.debugOtp == null) "OTP sent to +91 $phone." else "Development OTP: ${result.debugOtp}",
                    ),
                )
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                _events.send(OtpEvent.Message(e.userMessage(FALLBACK)))
            } finally {
                _state.update { it.copy(sending = false) }
            }
        }
    }

    fun verifyOtp(rawPhone: String, rawOtp: String) {
        val s = _state.value
        if (s.sending || s.verifying) return
        val phone = digits(rawPhone)
        val otp = rawOtp.trim()
        if (!PHONE.matches(phone)) {
            _events.trySend(OtpEvent.Message("Enter a valid mobile number."))
            return
        }
        if (!OTP.matches(otp)) {
            _events.trySend(OtpEvent.Message("Enter the 6-digit OTP."))
            return
        }
        _state.update { it.copy(verifying = true) }
        viewModelScope.launch {
            try {
                session.verifyOtp(phone, otp)
                _events.send(OtpEvent.Authenticated)
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                _events.send(OtpEvent.Message(e.userMessage(FALLBACK)))
            } finally {
                _state.update { it.copy(verifying = false) }
            }
        }
    }

    fun changeNumber() {
        _state.update { it.copy(otpSent = false, debugOtp = null, prefillOtp = null) }
    }

    fun prefillConsumed() = _state.update { it.copy(prefillOtp = null) }

    companion object {
        private val PHONE = Regex("""^[6-9]\d{9}$""")
        private val OTP = Regex("""^\d{6}$""")
        private const val FALLBACK = "Unable to continue right now. Please try again."
    }
}

/** Binds the OTP view to [viewModel]; [onMessage] shows snackbars, [onAuthenticated] runs after verification. */
fun Fragment.bindOtpLogin(
    binding: ViewOtpLoginBinding,
    viewModel: OtpLoginViewModel,
    onMessage: (String) -> Unit,
    onAuthenticated: () -> Unit,
) {
    binding.otpAction.setOnClickListener {
        val phone = binding.phoneInput.text?.toString().orEmpty()
        if (viewModel.state.value.otpSent) {
            viewModel.verifyOtp(phone, binding.otpInput.text?.toString().orEmpty())
        } else {
            viewModel.sendOtp(phone)
        }
    }
    binding.changeNumber.setOnClickListener {
        binding.otpInput.setText("")
        viewModel.changeNumber()
        binding.phoneInput.post {
            binding.phoneInput.requestFocus()
            binding.phoneInput.selectAll()
        }
    }
    var wasSent = viewModel.state.value.otpSent
    launchOnStarted {
        launch {
            viewModel.state.collect { s ->
                val busy = s.sending || s.verifying
                binding.phoneInput.isEnabled = !s.otpSent && !busy
                binding.phoneLayout.isEnabled = !s.otpSent && !busy
                binding.otpSection.visibleIf(s.otpSent)
                binding.changeNumber.isEnabled = !busy
                binding.otpAction.isEnabled = !busy
                binding.otpAction.text = if (busy) "" else getString(if (s.otpSent) R.string.verify_continue else R.string.send_otp)
                binding.otpProgress.visibleIf(busy)
                binding.debugOtp.visibleIf(s.debugOtp != null)
                binding.debugOtp.text = "Development OTP: ${s.debugOtp}"
                s.prefillOtp?.let {
                    binding.otpInput.setText(it)
                    viewModel.prefillConsumed()
                }
                if (s.otpSent && !wasSent) {
                    binding.otpInput.requestFocus()
                    requireContext().getSystemService<InputMethodManager>()
                        ?.showSoftInput(binding.otpInput, InputMethodManager.SHOW_IMPLICIT)
                }
                wasSent = s.otpSent
            }
        }
        viewModel.events.collect { event ->
            when (event) {
                is OtpEvent.Message -> onMessage(event.text)
                OtpEvent.Authenticated -> onAuthenticated()
            }
        }
    }
}
